window.ref = {
	gameDiv: document.querySelector('.game'),
	playButton: document.querySelector('.play'),
	menuDiv: document.querySelector('.menu'),
	chatDiv: document.querySelector('.chatDiv'),
	chat: document.querySelector('.chat'),
	canvas: document.querySelector('.game-canvas'),
	gui: document.querySelector('.gui'),
	deathScreen: document.querySelector('.death-screen'),
	kills: document.querySelector('.kills'),
	deaths: document.querySelector('.deaths'),
	kdr: document.querySelector('.kdr'),
	accuracy: document.querySelector('.accuracy'),
	chatMessageDiv: document.querySelector('.chat-div'),
	highscore: document.querySelector('.highscore'),
}